Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -26,21 +26,23 @@ jobs:
     - name: Setup Google Cloud SDK
       uses: google-github-actions/setup-gcloud@main
       with:
-        project_id: plenary-totem-425005-c3
+        project_id: qwiklabs-gcp-02-43702da4cac4
         service_account_key: ${{ secrets.GCP_SA_KEY }}
         export_default_credentials: true
 
-
+    - name: Stop JAR on GCP Compute Engine if running
+      run: |
+        gcloud compute ssh --zone=asia-south1-c student-04-334bf911c2e4@demoapp --command="if pgrep -f DemoApp-0.0.1-SNAPSHOT.jar > /dev/null; then sudo pkill -f DemoApp-0.0.1-SNAPSHOT.jar; else echo 'No process found'; fi"
         
     - name: Copy JAR to GCP Compute Engine
       run: |
-        gcloud compute scp --zone=asia-south1-c target/*.jar meenak_sharma2008@instance-20240601-130107:~
+        gcloud compute scp --zone=asia-south1-c target/*.jar student-04-334bf911c2e4@demoapp:~
 
     - name: Start JAR on GCP Compute Engine
       run: |
-        gcloud compute ssh --zone=asia-south1-c meenak_sharma2008@instance-20240601-130107 --command="screen -dm java -jar ~/DemoApp-0.0.1-SNAPSHOT.jar"
+        gcloud compute ssh --zone=asia-south1-c student-04-334bf911c2e4@demoapp --command="screen -dm java -jar ~/DemoApp-0.0.1-SNAPSHOT.jar"
         sleep 20
-        gcloud compute ssh --zone=asia-south1-c meenak_sharma2008@instance-20240601-130107 --command="if pgrep -f DemoApp-0.0.1-SNAPSHOT.jar > /dev/null; then echo 'Server started'; else echo 'Server failed to start'; exit 1; fi"
+        gcloud compute ssh --zone=asia-south1-c student-04-334bf911c2e4@demoapp --command="if pgrep -f DemoApp-0.0.1-SNAPSHOT.jar > /dev/null; then echo 'Server started'; else echo 'Server failed to start'; exit 1; fi"
 
 
 # Change project_id, service_account_key, --zone, jar_name
